sonar.projectKey=BBroerse_book-tracking
sonar.organization=bbroerse-1
sonar.projectName=book-tracking

sonar.sources=./
sonar.exclusions=**/node_modules/**, **/dist/**,**/main/resources/**

sonar.typescript.tsconfigPath=frontend/tsconfig.json

sonar.java.binaries=backend/**/target/classes

sonar.test.inclusions=backend/src/test/**/*.java, frontend/tests/**/*.ts
